<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2b1d40d3d01b4d8a191ddbd47c0d14cd
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Ddeboer\\Imap\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ddeboer\\Imap\\' => 
        array (
            0 => __DIR__ . '/..' . '/ddeboer/imap/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2b1d40d3d01b4d8a191ddbd47c0d14cd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2b1d40d3d01b4d8a191ddbd47c0d14cd::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
